package mobi.librera.libgoogle;

import android.app.Activity;
import android.widget.Toast;

import android.app.AlertDialog;

import com.foobnix.LibreraApp;
import com.foobnix.ai.IapStub;
import com.foobnix.model.AppProfile;
import com.foobnix.model.AppSP;
import com.foobnix.pdf.info.AppsConfig;
import com.foobnix.pdf.info.R;
import com.foobnix.pdf.info.Urls;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Unified purchase entry point (IAP STUB — billing NOT integrated yet).
 *
 * The pro flavor is the ad+IAP flagship: buying the IAP unlocks the pro
 * features. The unlock state is a build-time stub ({@link IapStub#UNLOCKED},
 * generated by the gradle generateIapStubSource task) ORed with the
 * device-local purchase flag (AppSP.iapProUnlocked) set by the stub purchase
 * dialog below, so both the locked and the stub-unlocked builds can be
 * verified end-to-end. When the Play billing integration lands, replace the
 * bodies of isProUnlocked()/launchPurchaseFlow()/restorePurchases() with real
 * com.android.billingclient calls (billing 8.x is already declared in
 * gradle/libs.versions.toml) — all gating points call exactly these methods.
 *
 * The fdroid flavor never unlocks and launchPurchaseFlow() jumps to the
 * website instead of showing a purchase dialog.
 */
public class BillingManager {

    /** Stub purchase order id (last 4 digits are shown on the Pro card). */
    private static final String STUB_ORDER_ID = "IAP-STUB-2026-8888";

    public BillingManager(LibreraApp libreraApp) {
    }

    /**
     * Whether the pro unlock (IAP) has been purchased. Hard false for every
     * non-pro flavor (fdroid has no pro features and no IAP by design).
     */
    public static boolean isProUnlocked() {
        if (!AppsConfig.isProFlavor()) {
            return false;
        }
        return IapStub.UNLOCKED || AppSP.get().iapProUnlocked;
    }

    /** Display name of the unlock channel (stub: local key; future: App Store / 小米 / 华为). */
    public static String getChannelText(Activity a) {
        return a.getString(R.string.pro_channel_local_key);
    }

    /** Purchase time shown on the Pro card, "" when not stub-purchased. */
    public static String getPurchaseTimeText(Activity a) {
        long t = AppSP.get().iapPurchaseTime;
        if (t <= 0 && IapStub.UNLOCKED) {
            // -PiapStub=true build without a runtime stub purchase yet:
            // fall back to the build-time stub purchase moment
            t = IapStub.STUB_PURCHASE_TIME;
        }
        if (t <= 0) {
            return "";
        }
        return new SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(new Date(t));
    }

    /** Last 4 characters of the (stub) order id, "" when not stub-purchased. */
    public static String getOrderIdSuffix() {
        String id = AppSP.get().iapOrderId;
        if ((id == null || id.length() == 0) && IapStub.UNLOCKED) {
            id = STUB_ORDER_ID;
        }
        if (id == null || id.length() == 0) {
            return "";
        }
        return id.length() <= 4 ? id : id.substring(id.length() - 4);
    }

    /**
     * Opens the purchase flow for the pro unlock. fdroid jumps to the
     * website (no IAP there); pro shows the STUB purchase dialog that sets
     * the device-local unlock flag, so the whole locked→active flow can be
     * verified before the real billing integration.
     *
     * @param onRefresh called after the state may have changed (UI refresh)
     */
    public static void launchPurchaseFlow(Activity a, Runnable onRefresh) {
        if (a == null || a.isDestroyed() || a.isFinishing()) {
            return;
        }
        if (!AppsConfig.isProFlavor()) {
            // fdroid: no IAP — go to the official website
            Urls.open(a, a.getString(R.string.my_site));
            return;
        }
        if (isProUnlocked()) {
            if (onRefresh != null) {
                onRefresh.run();
            }
            return;
        }
        new AlertDialog.Builder(a)
                .setTitle(R.string.pro_upgrade_btn)
                .setMessage(R.string.pro_stub_purchase_msg)
                .setPositiveButton(R.string.pro_stub_buy, (d, w) -> {
                    AppSP.get().iapProUnlocked = true;
                    AppSP.get().iapPurchaseTime = System.currentTimeMillis();
                    AppSP.get().iapOrderId = STUB_ORDER_ID;
                    AppProfile.save(a);
                    Toast.makeText(a, R.string.pro_toast_purchased, Toast.LENGTH_SHORT).show();
                    if (onRefresh != null) {
                        onRefresh.run();
                    }
                })
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }

    /** STUB restore: with the stub there is nothing to query — just refresh. */
    public static void restorePurchases(Activity a, Runnable onRefresh) {
        if (a == null) {
            return;
        }
        Toast.makeText(a, R.string.pro_toast_restored, Toast.LENGTH_SHORT).show();
        if (onRefresh != null) {
            onRefresh.run();
        }
    }

    /** STUB entitlement management: real implementation opens the store console. */
    public static void manageEntitlements(Activity a) {
        if (a == null) {
            return;
        }
        Toast.makeText(a, R.string.pro_toast_manage, Toast.LENGTH_SHORT).show();
    }

    /**
     * STUB refund/invalidation: clears the device-local unlock flag so the
     * Pro card falls back to "升级 Pro". Long-press "Pro 已激活" on the
     * settings card. TODO(IAP): replace with real purchase-state polling.
     */
    public static void simulateRefund(Activity a, Runnable onRefresh) {
        if (a == null || a.isDestroyed() || a.isFinishing()) {
            return;
        }
        new AlertDialog.Builder(a)
                .setTitle(R.string.pro_refund_title)
                .setMessage(R.string.pro_refund_msg)
                .setPositiveButton(android.R.string.ok, (d, w) -> {
                    AppSP.get().iapProUnlocked = false;
                    AppSP.get().iapPurchaseTime = 0;
                    AppSP.get().iapOrderId = "";
                    AppProfile.save(a);
                    Toast.makeText(a, R.string.pro_toast_refunded, Toast.LENGTH_SHORT).show();
                    if (onRefresh != null) {
                        onRefresh.run();
                    }
                })
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }
}
