package mobi.librera.libgoogle;

import android.app.Activity;
import android.app.AlertDialog;
import android.widget.Toast;

import com.foobnix.model.AppProfile;
import com.foobnix.model.AppSP;
import com.foobnix.pdf.info.AppsConfig;
import com.foobnix.pdf.info.R;
import com.foobnix.pdf.info.Urls;

/**
 * IAP STUB delegate (billing NOT integrated on this channel yet) — the
 * bodies moved here verbatim from the old BillingManager. Used by the
 * src/admobAds and src/noAds source sets via their BillingDelegateFactory.
 *
 * The pro flavor is the ad+IAP flagship: the unlock state is the build-time
 * stub ({@link com.foobnix.ai.IapStub#UNLOCKED}, generated by the gradle
 * generateIapStubSource task) ORed with the device-local purchase flag
 * (AppSP.iapProUnlocked) set by the stub purchase dialog, so both the locked
 * and the stub-unlocked builds can be verified end-to-end. When the Play
 * billing integration lands, replace this class with a real
 * com.android.billingclient delegate.
 *
 * The fdroid flavor never unlocks and launchPurchaseFlow() jumps to the
 * website instead of showing a purchase dialog.
 */
public class StubBillingDelegate implements BillingDelegate {

    /** Stub purchase order id (last 4 digits are shown on the Pro card). */
    static final String STUB_ORDER_ID = "IAP-STUB-2026-8888";

    /**
     * Whether the pro unlock (IAP) has been purchased. Hard false for every
     * non-pro flavor (fdroid has no pro features and no IAP by design).
     *
     * TEMPORARY (2026-09, v1.3.2): the pro flavor unlocks everything by
     * default so the remote-reading features can be verified on real
     * devices without the stub purchase. Restore the original
     * {@code IapStub.UNLOCKED || AppSP.get().iapProUnlocked} logic when the
     * real billing integration lands.
     */
    @Override
    public boolean isProUnlocked() {
        if (!AppsConfig.isProFlavor()) {
            return false;
        }
        return true;
    }

    /** Display name of the unlock channel (stub: local key; future: App Store / 小米 / 华为). */
    @Override
    public String getChannelText(Activity a) {
        return a.getString(R.string.pro_channel_local_key);
    }

    /**
     * Opens the purchase flow for the pro unlock. fdroid jumps to the
     * website (no IAP there); pro shows the STUB purchase dialog that sets
     * the device-local unlock flag, so the whole locked→active flow can be
     * verified before the real billing integration.
     */
    @Override
    public void launchPurchaseFlow(Activity a, Runnable onRefresh) {
        if (a == null || a.isDestroyed() || a.isFinishing()) {
            return;
        }
        if (!AppsConfig.isProFlavor()) {
            // fdroid: no IAP — go to the official website
            Urls.open(a, a.getString(R.string.my_site));
            return;
        }
        if (isProUnlocked()) {
            if (onRefresh != null) {
                onRefresh.run();
            }
            return;
        }
        new AlertDialog.Builder(a)
                .setTitle(R.string.pro_upgrade_btn)
                .setMessage(R.string.pro_stub_purchase_msg)
                .setPositiveButton(R.string.pro_stub_buy, (d, w) -> {
                    AppSP.get().iapProUnlocked = true;
                    AppSP.get().iapPurchaseTime = System.currentTimeMillis();
                    AppSP.get().iapOrderId = STUB_ORDER_ID;
                    AppProfile.save(a);
                    Toast.makeText(a, R.string.pro_toast_purchased, Toast.LENGTH_SHORT).show();
                    if (onRefresh != null) {
                        onRefresh.run();
                    }
                })
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }

    /** STUB restore: with the stub there is nothing to query — just refresh. */
    @Override
    public void restorePurchases(Activity a, Runnable onRefresh) {
        if (a == null) {
            return;
        }
        Toast.makeText(a, R.string.pro_toast_restored, Toast.LENGTH_SHORT).show();
        if (onRefresh != null) {
            onRefresh.run();
        }
    }

    /** STUB entitlement management: real implementation opens the store console. */
    @Override
    public void manageEntitlements(Activity a) {
        if (a == null) {
            return;
        }
        Toast.makeText(a, R.string.pro_toast_manage, Toast.LENGTH_SHORT).show();
    }

    /** STUB: nothing to sync without a billing backend. */
    @Override
    public void syncOwnershipSilently(Activity a) {
    }
}
